# Generated by Django 6.0.6 on 2026-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagevault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedimage',
            name='converted_file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convertedimage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
